version: "3.3"
services:
    traefik:
        image: traefik:2.5
        restart: unless-stopped
        ports:
           
            - 8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/traefik.toml
    todolist:
        build : .
        ports:
            - 8081:8080

        labels:
            - "traefik.http.routers.todolist.rule=PathPrefix(`/app`)"
            - "traefik.http.middlewares.todolist.stripPrefix.prefixes=/app"
            - "traefik.http.routers.todolist.middlewares=todolist@docker"
         deploy:
             replicas: 3
